// user types
export const USER_START = 'USER_START';
export const USER_ERROR = 'USER_ERROR';

export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_PROPERTY = 'USER_SET_PROPERTY';
export const USER_RESET_ERROR = 'USER_RESET_ERROR';

// transactions
export const TRANSACTION_START = 'TRANSACTION_START';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';

export const TRANSACTION_USER_LIST_SUCCESS = 'TRANSACTION_USER_LIST_SUCCESS';
export const TRANSACTION_PAYMENT_SUCCESS = 'TRANSACTION_PAYMENT_SUCCESS';
export const TRANSACTION_SET_PROPERTY = 'TRANSACTION_SET_PROPERTY';
export const TRANSACTION_HISTORY_SUCCESS = 'TRANSACTION_HISTORY_SUCCESS';



